server:
  port: 8081

app:
  id: common-logging

spring:
  application:
    name: common-logging

  cloud:
    config:
      uri: http://localhost:8080

  profiles:
    active: local

  jmx:
    enabled: true

  main:
    allow-bean-definition-overriding: true

---
spring:
  profiles: local

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: alpha

---
spring:
  profiles: staging

---
spring:
  profiles: live
