server:
  port: 8081

app:
  id: common-logging

spring:
  application:
    name: common-logging
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

  profiles:
    active: local

  jmx:
    enabled: true

  main:
    allow-bean-definition-overriding: true

